### ISSUE TITLE
Problem przy konfiguracji na Fedora 25

### ISSUE THREAD

**Issue by michalsadkiewicz** [linuxpolska/WEBSSOOpenSourceDay2017#2]
Witam, Fedora 25 świeża instalacja, zainstalowałem VirtualBox 5.1.22r115126, Vagrant 1.8.5, skolonowany projekt. Przy instalacji pluginu vagranta dostaję błąd jak poniżej. Co jest jego przyczyną i jak rozwiązać problem?
Pozdrawiam

```
[root@localhost WEBSSOOpenSourceDay2017]# vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.18), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.18'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /root/.vagrant.d/gems/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby -r ./siteconf20170516-7820-1abzs6q.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/gems/ffi-1.9.18 for inspection.
Results logged to /root/.vagrant.d/gems/extensions/x86_64-linux/2.3.0/ffi-1.9.18/gem_make.out
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /root/.vagrant.d/gems/gems/json-2.1.0/ext/json/ext/generator
/usr/bin/ruby -r ./siteconf20170516-7820-kc79pe.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/gems/json-2.1.0 for inspection.
Results logged to /root/.vagrant.d/gems/extensions/x86_64-linux/2.3.0/json-2.1.0/gem_make.out

```

**Comment by kardasa** [comment]
Czy wagrant jest instalowany z Repozytoriim pakietów Fedory?
Czy podjęto próbę instalacji brakującej zalężności zgodnie z wyraźnym komunikatem:
gem install ffi -v '1.9.18'
Ja mam u siebie ffi 1.9.14 - jak 1.9.18 się instaluje można spróbować starszej wersji.
W razie problemów aktualizacja Vagranta do wersji ze stony może pomóc. 
W większości przypadków nowy Vagrant nie sprawia z tym projektem problemów.

**Comment by michalsadkiewicz** [comment]
Vagrant był instalowany z repo Fedory
Natomiast próba instalacji powyższej zależności również kończy sie błędem (to samo dla 1.9.18 i 1.9.14)

```
[root@localhost WEBSSOOpenSourceDay2017]# gem install ffi -v '1.9.18'
Fetching: ffi-1.9.18.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/share/gems/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby -r ./siteconf20170516-11118-sxg901.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /usr/local/share/gems/gems/ffi-1.9.18 for inspection.
Results logged to /usr/local/lib64/gems/ruby/ffi-1.9.18/gem_make.out


[root@localhost WEBSSOOpenSourceDay2017]# cat /usr/local/lib64/gems/ruby/ffi-1.9.18/gem_make.out
current directory: /usr/local/share/gems/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby -r ./siteconf20170516-11118-sxg901.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

```

**Comment by kardasa** [comment]
dnf -y install gcc ruby-devel 
powinno pomóc w budowaniu brakujących pakietów

**Comment by michalsadkiewicz** [comment]
Niestety nadal są błędy:

```
[root@localhost WEBSSOOpenSourceDay2017]# vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.18), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.18'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /root/.vagrant.d/gems/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby -r ./siteconf20170516-4535-f5dav6.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib64
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/share/ruby/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/ruby/mkmf.rb:587:in `try_cpp'
	from /usr/share/ruby/mkmf.rb:1091:in `block in have_header'
	from /usr/share/ruby/mkmf.rb:942:in `block in checking_for'
	from /usr/share/ruby/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/share/ruby/mkmf.rb:320:in `open'
	from /usr/share/ruby/mkmf.rb:350:in `block in postpone'
	from /usr/share/ruby/mkmf.rb:320:in `open'
	from /usr/share/ruby/mkmf.rb:346:in `postpone'
	from /usr/share/ruby/mkmf.rb:941:in `checking_for'
	from /usr/share/ruby/mkmf.rb:1090:in `have_header'
	from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /root/.vagrant.d/gems/extensions/x86_64-linux/2.3.0/ffi-1.9.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/gems/ffi-1.9.18 for inspection.
Results logged to /root/.vagrant.d/gems/extensions/x86_64-linux/2.3.0/ffi-1.9.18/gem_make.out
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /root/.vagrant.d/gems/gems/json-2.1.0/ext/json/ext/generator
/usr/bin/ruby -r ./siteconf20170516-4535-1917b2v.rb extconf.rb
creating Makefile

current directory: /root/.vagrant.d/gems/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean
rm -f 
rm -f generator.so  *.o  *.bak mkmf.log .*.time

current directory: /root/.vagrant.d/gems/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -DJSON_GENERATOR    -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -fPIC -m64 -o generator.o -c generator.c
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
Makefile:239: polecenia dla obiektu 'generator.o' nie powiodły się
make: *** [generator.o] Błąd 1

make failed, exit code 2

Gem files will remain installed in /root/.vagrant.d/gems/gems/json-2.1.0 for inspection.
Results logged to /root/.vagrant.d/gems/extensions/x86_64-linux/2.3.0/json-2.1.0/gem_make.out

```
```
[root@localhost WEBSSOOpenSourceDay2017]# cat /root/.vagrant.d/gems/extensions/x86_64-linux/2.3.0/ffi-1.9.18/mkmf.log
"pkg-config --exists libffi"
package configuration for libffi is not found
"gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -fPIC conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lpthread -ldl -lcrypt -lm   -lc"
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```
czego jeszcze brakuje? Czy mam przeinstalować vagrant na 1.9.5 (ze strony) czy nic to nie da?

**Comment by kardasa** [comment]
No to lecimy dalej z zależnościami dla gcc:
dnf install redhat-rpm-config

Zobaczymy co jeszcze nam wyjdzie

**Comment by michalsadkiewicz** [comment]
Ok, po przeinstalowaniu na vagrant 1.9.5 pluginy się zainstalowały.. Był jeszcze problem z instalacją VB, ale poradziłem sobie, teraz uruchomiłem vagrant up i narazie leci poprawnie... zobaczymy czy przejdzie

**Comment by kardasa** [comment]
Nastaw się na długie czekanie tam jakiś GB jest do pobrania.

**Comment by michalsadkiewicz** [comment]
leci w większości na zielono, ale też są fragmety czerwone, mam się tym przejmować?

```

==> 389ds.websso.linuxpolska.pl: + '[' -f /vagrant/provision/variables ']'
==> 389ds.websso.linuxpolska.pl: + source /vagrant/provision/variables
==> 389ds.websso.linuxpolska.pl: ++ : Common
==> 389ds.websso.linuxpolska.pl: ++ TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: ++ : EPEL
==> 389ds.websso.linuxpolska.pl: ++ EPEL_VERSION=7-9
==> 389ds.websso.linuxpolska.pl: ++ EPEL_URL=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
==> 389ds.websso.linuxpolska.pl: ++ EPEL_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: ++ : JDK
==> 389ds.websso.linuxpolska.pl: ++ JDK_VERSION=8u121
==> 389ds.websso.linuxpolska.pl: ++ JDK_BUILD=b13
==> 389ds.websso.linuxpolska.pl: ++ JDK_BASE_URL_8=http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121
==> 389ds.websso.linuxpolska.pl: +++ echo http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121
==> 389ds.websso.linuxpolska.pl: +++ rev
==> 389ds.websso.linuxpolska.pl: +++ cut -d / -f1
==> 389ds.websso.linuxpolska.pl: +++ rev
==> 389ds.websso.linuxpolska.pl: ++ JDK_VERSION=jdk-8u121
==> 389ds.websso.linuxpolska.pl: ++ JDK_PLATFORM=-linux-x64.rpm
==> 389ds.websso.linuxpolska.pl: ++ JDK_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: ++ : CAS
==> 389ds.websso.linuxpolska.pl: ++ CAS_VERSION=5.0
==> 389ds.websso.linuxpolska.pl: ++ CAS_URL=https://github.com/apereo/cas-overlay-template
==> 389ds.websso.linuxpolska.pl: ++ CAS_BUILDDIR=/tmp
==> 389ds.websso.linuxpolska.pl: ++ CAS_TARGET=/vagrant/tmp/auth.war
==> 389ds.websso.linuxpolska.pl: ++ CAS_SERVICE_MGMNT_URL=https://github.com/apereo/cas-services-management-overlay
==> 389ds.websso.linuxpolska.pl: ++ CAS_SERVICE_MGMNT_TARGET=/vagrant/tmp/cas-management.war
==> 389ds.websso.linuxpolska.pl: ++ : Tomcat
==> 389ds.websso.linuxpolska.pl: ++ TOMCAT_VERSION=8.5.15
==> 389ds.websso.linuxpolska.pl: ++ TOMCAT_URL=http://ftp.piotrkosoft.net/pub/mirrors/ftp.apache.org/tomcat/tomcat-8/v8.5.15/bin/apache-tomcat-8.5.15.tar.gz
==> 389ds.websso.linuxpolska.pl: ++ TOMCAT_DIR=/opt
==> 389ds.websso.linuxpolska.pl: ++ TOMCAT_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: ++ : KeyKloak
==> 389ds.websso.linuxpolska.pl: ++ KEYCLOAK_VERSION=3.0.0.Final
==> 389ds.websso.linuxpolska.pl: ++ KEYCLOAK_URL=https://downloads.jboss.org/keycloak/3.0.0.Final/keycloak-3.0.0.Final.tar.gz
==> 389ds.websso.linuxpolska.pl: ++ KEYCLOAK_DIR=/opt
==> 389ds.websso.linuxpolska.pl: ++ KEYCLOAK_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: ++ : Applications
==> 389ds.websso.linuxpolska.pl: ++ APP_NAMES='wordpress liferay'
==> 389ds.websso.linuxpolska.pl: ++ : Wordpress SAML Plugin
==> 389ds.websso.linuxpolska.pl: ++ WORDPRESS_SAML_URL=https://downloads.wordpress.org/plugin/onelogin-saml-sso.zip
==> 389ds.websso.linuxpolska.pl: ++ : Wordpress CAS plugin
==> 389ds.websso.linuxpolska.pl: ++ WORDPRESS_CAS_URL=https://downloads.wordpress.org/plugin/wp-cassify.2.0.4.zip
==> 389ds.websso.linuxpolska.pl: ++ : LifreRay Portal CE
==> 389ds.websso.linuxpolska.pl: ++ LIFERAY_MAJOR_VERSION=7.0.2%20GA3
==> 389ds.websso.linuxpolska.pl: ++ LIFERAY_MINOR_VERSION=7.0-ga3-20160804222206210
==> 389ds.websso.linuxpolska.pl: ++ LIFERAY_URL=https://freefr.dl.sourceforge.net/project/lportal/Liferay%20Portal/7.0.2%20GA3/liferay-ce-portal-tomcat-7.0-ga3-20160804222206210.zip
==> 389ds.websso.linuxpolska.pl: ++ LIFERAY_DIR=/opt/liferay-ce-portal-7.0-ga3
==> 389ds.websso.linuxpolska.pl: ++ LIFERAY_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: + '[' -z 7-9 ']'
==> 389ds.websso.linuxpolska.pl: + '[' -z http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm ']'
==> 389ds.websso.linuxpolska.pl: + '[' -z /vagrant/tmp ']'
==> 389ds.websso.linuxpolska.pl: ++ basename http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
==> 389ds.websso.linuxpolska.pl: + EPEL_TARGET_FILE=/vagrant/tmp/epel-release-7-9.noarch.rpm
==> 389ds.websso.linuxpolska.pl: + '[' -f /vagrant/provision/bootstrap-node-rhel.sh ']'
==> 389ds.websso.linuxpolska.pl: + source /vagrant/provision/bootstrap-node-rhel.sh
==> 389ds.websso.linuxpolska.pl: ++ set -x
==> 389ds.websso.linuxpolska.pl: ++ '[' -f /vagrant/provision/variables ']'
==> 389ds.websso.linuxpolska.pl: ++ source /vagrant/provision/variables
==> 389ds.websso.linuxpolska.pl: +++ : Common
==> 389ds.websso.linuxpolska.pl: +++ TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: +++ : EPEL
==> 389ds.websso.linuxpolska.pl: +++ EPEL_VERSION=7-9
==> 389ds.websso.linuxpolska.pl: +++ EPEL_URL=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
==> 389ds.websso.linuxpolska.pl: +++ EPEL_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: +++ : JDK
==> 389ds.websso.linuxpolska.pl: +++ JDK_VERSION=8u121
==> 389ds.websso.linuxpolska.pl: +++ JDK_BUILD=b13
==> 389ds.websso.linuxpolska.pl: +++ JDK_BASE_URL_8=http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121
==> 389ds.websso.linuxpolska.pl: ++++ echo http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121
==> 389ds.websso.linuxpolska.pl: ++++ rev
==> 389ds.websso.linuxpolska.pl: ++++ cut -d / -f1
==> 389ds.websso.linuxpolska.pl: ++++ rev
==> 389ds.websso.linuxpolska.pl: +++ JDK_VERSION=jdk-8u121
==> 389ds.websso.linuxpolska.pl: +++ JDK_PLATFORM=-linux-x64.rpm
==> 389ds.websso.linuxpolska.pl: +++ JDK_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: +++ : CAS
==> 389ds.websso.linuxpolska.pl: +++ CAS_VERSION=5.0
==> 389ds.websso.linuxpolska.pl: +++ CAS_URL=https://github.com/apereo/cas-overlay-template
==> 389ds.websso.linuxpolska.pl: +++ CAS_BUILDDIR=/tmp
==> 389ds.websso.linuxpolska.pl: +++ CAS_TARGET=/vagrant/tmp/auth.war
==> 389ds.websso.linuxpolska.pl: +++ CAS_SERVICE_MGMNT_URL=https://github.com/apereo/cas-services-management-overlay
==> 389ds.websso.linuxpolska.pl: +++ CAS_SERVICE_MGMNT_TARGET=/vagrant/tmp/cas-management.war
==> 389ds.websso.linuxpolska.pl: +++ : Tomcat
==> 389ds.websso.linuxpolska.pl: +++ TOMCAT_VERSION=8.5.15
==> 389ds.websso.linuxpolska.pl: +++ TOMCAT_URL=http://ftp.piotrkosoft.net/pub/mirrors/ftp.apache.org/tomcat/tomcat-8/v8.5.15/bin/apache-tomcat-8.5.15.tar.gz
==> 389ds.websso.linuxpolska.pl: +++ TOMCAT_DIR=/opt
==> 389ds.websso.linuxpolska.pl: +++ TOMCAT_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: +++ : KeyKloak
==> 389ds.websso.linuxpolska.pl: +++ KEYCLOAK_VERSION=3.0.0.Final
==> 389ds.websso.linuxpolska.pl: +++ KEYCLOAK_URL=https://downloads.jboss.org/keycloak/3.0.0.Final/keycloak-3.0.0.Final.tar.gz
==> 389ds.websso.linuxpolska.pl: +++ KEYCLOAK_DIR=/opt
==> 389ds.websso.linuxpolska.pl: +++ KEYCLOAK_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: +++ : Applications
==> 389ds.websso.linuxpolska.pl: +++ APP_NAMES='wordpress liferay'
==> 389ds.websso.linuxpolska.pl: +++ : Wordpress SAML Plugin
==> 389ds.websso.linuxpolska.pl: +++ WORDPRESS_SAML_URL=https://downloads.wordpress.org/plugin/onelogin-saml-sso.zip
==> 389ds.websso.linuxpolska.pl: +++ : Wordpress CAS plugin
==> 389ds.websso.linuxpolska.pl: +++ WORDPRESS_CAS_URL=https://downloads.wordpress.org/plugin/wp-cassify.2.0.4.zip
==> 389ds.websso.linuxpolska.pl: +++ : LifreRay Portal CE
==> 389ds.websso.linuxpolska.pl: +++ LIFERAY_MAJOR_VERSION=7.0.2%20GA3
==> 389ds.websso.linuxpolska.pl: +++ LIFERAY_MINOR_VERSION=7.0-ga3-20160804222206210
==> 389ds.websso.linuxpolska.pl: +++ LIFERAY_URL=https://freefr.dl.sourceforge.net/project/lportal/Liferay%20Portal/7.0.2%20GA3/liferay-ce-portal-tomcat-7.0-ga3-20160804222206210.zip
==> 389ds.websso.linuxpolska.pl: +++ LIFERAY_DIR=/opt/liferay-ce-portal-7.0-ga3
==> 389ds.websso.linuxpolska.pl: +++ LIFERAY_TARGET=/vagrant/tmp
==> 389ds.websso.linuxpolska.pl: ++ : Tools useful for debugging and development + all editors to make every one happy - use what u like
==> 389ds.websso.linuxpolska.pl: ++ yum -y install vim telnet nmap tcpdump git openldap-clients nano emacs-nox bash-completion bash-completion-extras chrony

```

**Comment by kardasa** [comment]
Nie norma :D jak coś listuje wyświetla to na czerwono.
Będziesz miał jeszcze komunikaty o niepodpisanych pakietach - nie przejmuj się - one po prostu są nie podpisane.

**Comment by michalsadkiewicz** [comment]
Ok, potwierdzam, udało się wszystko skonfigurować, strony się otwierają w VB jest dodanych 5 maszyn.  Największym problemem jak widac, była wersja vagranta - na 1.8.5 która jest w repo fedory nie poszło, dopiero po przeinstalowaniu na wersję 1.9.5 ze strony zadziałało.
Dzięki i do zobaczenia jutro na warsztatach!

**Comment by kardasa** [comment]
Ja mam dokładnie taką Fedorę i taki Vagrant. Problem w tym, że Vagrant z repozytorium nie instaluje zależności dla języka Ruby i kompilatorów a ich spełnienie jest jest mozolne. Vagrant ze strony Hashicorpa ma zależności przynajmniej dla Ruby w zdecydowanej większości lokalnie wbudowane. Cieszę się, że działa, Do zobaczenia
